---
- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{username}}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: Update packages
  apt:
    update_cache: true
    upgrade: true

- name: Install packages
  apt:
    pkg:
      - docker.io
      - docker-compose
      - vim

- name: Clone a github repository
  git:
    repo: https://github.com/Jakub3628800/crossroads.git
    dest: /home/crossroads
    clone: true
    update: true
